# Generated by Django 3.1.3 on 2020-11-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('current_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account_id', to='users.user')),
                ('to_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account_id', to='users.user')),
            ],
        ),
    ]
